-- Conduce+ v0.2 — Esquema persistente en Supabase/PostgreSQL
-- Ejecutar una sola vez en Supabase > SQL Editor > New query.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key default gen_random_uuid(),
    display_name text not null check (char_length(display_name) between 2 and 40),
    name_key text not null unique check (char_length(name_key) between 2 and 40),
    pin_hash text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.quiz_sessions (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    mode text not null check (mode in ('daily', 'practice')),
    date_key date not null,
    question_ids jsonb not null check (jsonb_typeof(question_ids) = 'array'),
    status text not null default 'active' check (status in ('active', 'completed')),
    created_at timestamptz not null default now(),
    completed_at timestamptz
);

create unique index if not exists uq_one_daily_session_per_profile
    on public.quiz_sessions(profile_id, date_key)
    where mode = 'daily';

create index if not exists idx_sessions_profile_created
    on public.quiz_sessions(profile_id, created_at);

create table if not exists public.attempts (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.quiz_sessions(id) on delete cascade,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    question_id text not null,
    topic text not null,
    difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
    selected_id text not null,
    correct_id text not null,
    is_correct boolean not null,
    response_ms integer not null default 0 check (response_ms >= 0),
    answered_at timestamptz not null default now(),
    unique(session_id, question_id)
);

create index if not exists idx_attempts_profile_answered
    on public.attempts(profile_id, answered_at);

-- Evita que una respuesta sea asociada a un perfil diferente al dueño de la sesión.
create or replace function public.enforce_attempt_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (
        select 1
        from public.quiz_sessions s
        where s.id = new.session_id
          and s.profile_id = new.profile_id
    ) then
        raise exception 'profile_id does not match session owner' using errcode = '23514';
    end if;
    return new;
end;
$$;

drop trigger if exists trg_attempt_profile_matches on public.attempts;
create trigger trg_attempt_profile_matches
before insert or update on public.attempts
for each row execute function public.enforce_attempt_profile();

-- La app usa exclusivamente una Secret key guardada en el backend de Streamlit.
-- No se permite acceso directo con publishable/anon/authenticated.
alter table public.profiles enable row level security;
alter table public.quiz_sessions enable row level security;
alter table public.attempts enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.quiz_sessions from anon, authenticated;
revoke all on table public.attempts from anon, authenticated;

grant usage on schema public to service_role;
grant all on table public.profiles to service_role;
grant all on table public.quiz_sessions to service_role;
grant all on table public.attempts to service_role;
grant usage, select on all sequences in schema public to service_role;
